name: build image and push on docker hub and deploy on EKS
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}                                                                                               
      RELEASE_IMAGE: 7011347758/test${{ github.sha }}

    steps:
      - name: code check
        uses: actions/checkout@v3
        
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
    
      - name: Generate image tags
        id: docker_tags
        uses: anothrNick/github-tag-action@1.40.0
        env:
         GITHUB_TOKEN: ${{ secrets.TOKEN }}
         WITH_V: true
         
      - name: Build docker image and push docker image on docker hub 
        uses: mr-smithers-excellent/docker-build-push@v5.8
        with:
          image: 7011347758/test
          tags: ${{ steps.docker_tags.outputs.tag }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Deploy to Kubernetes cluster                                                                            
        uses: kodermax/kubectl-aws-eks@master                   
        with:                                                                                                         
         args: set image deployment/ecomm-app app=7011347758/test:${{ steps.docker_tags.outputs.tag }} --record


         ##